language: python
cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
dist: xenial
env:
  global:
  - TEST_DIR=/tmp/sklearn
  - OMP_NUM_THREADS=2
  - OPENBLAS_NUM_THREADS=2
  - PYTEST_VERSION=latest
matrix:
  include:
  - python: 3.7
    env:
    - CHECK_WARNINGS="true"
    - CI_CPU_COUNT="3"
  - python: 3.7
    env:
    - CHECK_WARNING="true"
    - BUILD_WITH_ICC="true"
    - CI_CPU_COUNT="3"
  - python: 3.7
    env:
    - CI_CPU_COUNT="8"
    os: linux
    arch: arm64
install: source build_tools/travis/install.sh
script:
- bash build_tools/travis/test_script.sh || travis_terminate 1
- bash build_tools/travis/test_docs.sh || travis_terminate 1
- bash build_tools/travis/test_pytest_soft_dependency.sh || travis_terminate 1
after_success: source build_tools/travis/after_success.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change
    on_failure: always
    on_start: never
before_script:
- bash test_mypy.sh
